### ISSUE TITLE
In script tag code not work

### ISSUE THREAD

**Issue by lzxb** [Yuyz0112/vue-type-check#4]
![image](https://user-images.githubusercontent.com/8424643/71171189-289d6b00-2298-11ea-829b-02ecae771682.png)

node -v
v12.6.0

**Comment by Yuyz0112** [comment]
I've seen someone experiencing this issue too but still could not reproduce it locally...

**Comment by lzxb** [comment]
Having looked at this problem today, I know how to reproduce it

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/99400974-962b9e80-2922-11eb-8b0d-5ddbca896fc1.png)

**Comment by lzxb** [comment]
Strict mode must be set to work

**Comment by lzxb** [comment]
建议使用更好的：https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc
